<?php /** @var DHLParcel_Shipping_Block_Jsdata_ServicePoint_Locator $this */ ?>
<script type="text/javascript">
    // Default locator data
    var DHLShipping_ServicePointAPIUrl = '<?php echo $this->getGatewayUrl(); ?>';
    var DHLShipping_ServicePointMapsAPIKey = '<?php echo $this->getMapsKey(); ?>';
    var DHLShipping_Texts_ChangePs = '<?php echo __('Other ServicePoint'); ?>';
    var DHLShipping_Texts_SelectPs = '<?php echo __('Select ServicePoint'); ?>';
    var DHLShipping_Texts_Distance = '<?php echo __('Distance'); ?>';
    var DHLShipping_FetchedPs = {};
    var DHLShipping_Language = '<?php echo $this->getLanguage(); ?>';
</script>
